presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: op1st/prow/pre-commit
    spec:
      containers:
        - image: quay.io/operate-first/opf-toolbox:v0.12.0
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          env:
            - name: HOME
              value: "."
