---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- rolebinding.yaml
- role.yaml
- route.yaml
- secret.yaml
- serviceaccount.yaml
- service.yaml
- servicemonitor.yaml
namePrefix: "{{name}}-"
configurations:
- .transformers.yaml
commonLabels:
  app.kubernetes.io/component: controller
