apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller
spec:
  endpoints:
    - path: /metrics
      port: webhook
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
