---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configurations:
  - .transformers.yaml
generators:
  - .ksops.yaml
namespace: "{{stage-namespace}}"
patchesStrategicMerge:
  - route.yaml
images:
  - name: controller
    newName: "{{image}}"
    newTag: v1.0.0
