---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example
spec:
  params:
    - name: CONTEXT
      type: string
      default: ""
    - name: SECRET_NAME
      type: string
  steps:
    - name: example
      image: example
      volumeMounts:
        - mountPath: /mnt/secret
          name: github-token
      env:
        - name: ORG_NAME
          valueFrom:
            secretKeyRef:
              name: $(params.SECRET_NAME)
              key: orgName
        - name: APP_ID
          valueFrom:
            secretKeyRef:
              name: peribolos-controller
              key: app_id
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.SECRET_NAME)
              key: token
      script: |
        #!/bin/sh

        echo "Org name: $ORG_NAME"
        echo "App ID: $APP_ID"
        echo "Event context:"
        echo '$(params.CONTEXT)' | yq e -P -
  volumes:
    - name: github-token
      secret:
        secretName: $(params.SECRET_NAME)
        items:
          - key: token
            path: token
        optional: false
