---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- onboarding.yaml
configurations:
- .transformers.yaml
namePrefix: "{{name}}-"
commonLabels:
  app.kubernetes.io/component: task
images:
- name: opf-toolbox
  newName: quay.io/operate-first/opf-toolbox:v0.5.0
- name: python
  newName: registry.access.redhat.com/ubi8/python-38
configMapGenerator:
- name: robozome
  files:
  - onboarding.patch
generatorOptions:
  disableNameSuffixHash: true
