---
apiVersion: tekton.dev/v1beta1
kind: task
metadata:
  name: run
spec:
  params:
    - name: PAYLOAD
      type: string
      default: ""
  steps:
    - name: clone-repo
      image: opf-toolbox
      script:
        #!/usr/bin/bash
        
        echo "Cloning repo"
        git clone https://github.com/tssala23/ReadIssuesTest.git
        cd ReadIssuesTest
        
    - name: create-patch
      image: opf-toolbox
      script:
        #!/usr/bin/bash
        
        echo '$(params.PAYLOAD)' | yq e "" -P - > /tmp/data.yaml
        mustache /tmp/data.yaml /mnt/config/robozome/onboarding.patch > /tmp/onboarding.patch
        
    - name: apply-push-patch
      image: opf-toolbox
      script:
        #!/usr/bin/bash
        
        git checkout -b "onboarding/$(yq e ".namespace" /tmp/data.yaml)"
        git apply /tmp/onboarding.patch
        git add .
        git commit -m "Onboarding request for $(yq e ".namespace" /tmp/data.yaml)"
        git push -u origin HEAD
        gh pr create -R *REPO NAME* --title "Onboarding request" --body "Onboarding request for $(yq e ".namespace" /tmp/data.yaml) to the $(yq e ".cluster" /tmp/data.yaml) cluster." -f
        
